"""empty message

Revision ID: 101e330a8957
Revises: 54ea98c3becc
Create Date: 2022-06-22 17:18:35.788228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101e330a8957'
down_revision = '54ea98c3becc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'user_id')
    # ### end Alembic commands ###
